from __future__ import annotations

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def create_fb_custom_fields():
    custom_fields = {
        "Company": [
            {
                "fieldname": "custom_kopos_qr_failure_variance_account",
                "label": "KoPOS QR Failure Variance Account",
                "description": (
                    "Company-scoped Expense ledger debited only when a pending QR "
                    "settlement is terminally failed with submitted accounting evidence"
                ),
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "default_currency",
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_duplicate_payment_clearing_account",
                "label": "KoPOS Duplicate QR Bank/Clearing Account",
                "description": (
                    "Company-scoped MYR Asset ledger debited when an additional "
                    "provider-paid Automatic QR attempt is recognized and credited "
                    "only when its exact provider refund is recorded"
                ),
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "custom_kopos_qr_failure_variance_account",
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_customer_liability_account",
                "label": "KoPOS QR Customer Refund Liability Account",
                "description": (
                    "Company-scoped MYR Liability ledger credited before a duplicate "
                    "provider payment can be marked refund_required"
                ),
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "custom_kopos_qr_duplicate_payment_clearing_account",
                "no_copy": 1,
                "translatable": 0,
            },
        ],
        "Item": [
            {
                "fieldname": "custom_fb_item_role",
                "label": "F&B Item Role",
                "fieldtype": "Select",
                "options": "\nSellable Drink\nIngredient\nPrep Item\nPackaging\nTool\nAsset Managed Gear",
                "insert_after": "item_group",
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_recipe_required",
                "label": "F&B Recipe Required",
                "fieldtype": "Check",
                "default": "0",
                "insert_after": "custom_fb_item_role",
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_default_recipe",
                "label": "F&B Default Recipe",
                "fieldtype": "Link",
                "options": "FB Recipe",
                "insert_after": "custom_fb_recipe_required",
                "depends_on": "eval:doc.custom_fb_recipe_required == 1",
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_track_theoretical_stock",
                "label": "Track Theoretical Stock",
                "fieldtype": "Check",
                "default": "0",
                "insert_after": "custom_fb_default_recipe",
                "translatable": 0,
            },
        ],
        "KoPOS Device": [
            {
                "fieldname": "inventory_report_schema_version",
                "label": "Inventory Report Schema Version",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_report_revision",
                "label": "Inventory Report Revision",
                "fieldtype": "Int",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_observed_at",
                "label": "Inventory Observed At",
                "fieldtype": "Datetime",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_report_received_at",
                "label": "Inventory Report Received At",
                "fieldtype": "Datetime",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_config_version",
                "label": "Inventory Device Config Version",
                "fieldtype": "Int",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_overlay_version",
                "label": "Inventory Overlay Version",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_overlay_hash",
                "label": "Inventory Overlay Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_sales_pending",
                "label": "Inventory Sales Pending",
                "fieldtype": "Int",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_sales_syncing",
                "label": "Inventory Sales Syncing",
                "fieldtype": "Int",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_sales_failed",
                "label": "Inventory Sales Failed",
                "fieldtype": "Int",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_sales_dead_letter",
                "label": "Inventory Sales Dead Letter",
                "fieldtype": "Int",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_oldest_unsaved_sale_at",
                "label": "Oldest Unsaved Sale At",
                "fieldtype": "Datetime",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_commands_pending",
                "label": "Inventory Commands Pending",
                "fieldtype": "Int",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_commands_failed",
                "label": "Inventory Commands Failed",
                "fieldtype": "Int",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "inventory_report_payload_hash",
                "label": "Inventory Report Payload Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
        ],
        "Sales Invoice": [
            {
                "fieldname": "custom_fb_order",
                "label": "F&B Order",
                "fieldtype": "Link",
                "options": "FB Order",
                "insert_after": "customer",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_shift",
                "label": "F&B Shift",
                "fieldtype": "Link",
                "options": "FB Shift",
                "insert_after": "custom_fb_order",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_device_id",
                "label": "Device ID",
                "fieldtype": "Data",
                "insert_after": "custom_fb_shift",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_event_project",
                "label": "Event/Project",
                "fieldtype": "Link",
                "options": "Project",
                "insert_after": "custom_fb_device_id",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_idempotency_key",
                "label": "Idempotency Key",
                "fieldtype": "Data",
                "insert_after": "custom_fb_event_project",
                "read_only": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_operational_status",
                "label": "Operational Status",
                "fieldtype": "Select",
                "options": "\nDraft\nSubmitted\nCancelled",
                "insert_after": "custom_fb_idempotency_key",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_void_idempotency_key",
                "label": "Void Idempotency Key",
                "fieldtype": "Data",
                "insert_after": "custom_fb_operational_status",
                "read_only": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_void_request_fingerprint",
                "label": "Void Request Fingerprint",
                "fieldtype": "Data",
                "insert_after": "custom_fb_void_idempotency_key",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_void_manager",
                "label": "Void Approved By Manager",
                "fieldtype": "Link",
                "options": "User",
                "insert_after": "custom_fb_void_request_fingerprint",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_void_approval_token_id",
                "label": "Void Approval Token ID",
                "fieldtype": "Data",
                "insert_after": "custom_fb_void_manager",
                "read_only": 1,
                "unique": 1,
                "translatable": 0,
            },
        ],
        "Material Request": [
            {
                "fieldname": "custom_kopos_inventory_fingerprint",
                "label": "KoPOS Inventory Fingerprint",
                "fieldtype": "Data",
                "unique": 1,
                "read_only": 1,
                "no_copy": 1,
            },
        ],
        "Purchase Order": [
            {
                "fieldname": "custom_kopos_inventory_fingerprint",
                "label": "KoPOS Inventory Fingerprint",
                "fieldtype": "Data",
                "unique": 1,
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_material_request",
                "label": "KoPOS Material Request",
                "fieldtype": "Link",
                "options": "Material Request",
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_plan_hash",
                "label": "KoPOS Plan Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_policy_hash",
                "label": "KoPOS Policy Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_quotation_hash",
                "label": "KoPOS Quotation Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "no_copy": 1,
            },
        ],
        "Sales Invoice Item": [
            {
                "fieldname": "custom_fb_order_line_ref",
                "label": "F&B Order Line Ref",
                "fieldtype": "Data",
                "insert_after": "item_name",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_resolved_sale",
                "label": "F&B Resolved Sale",
                "fieldtype": "Link",
                "options": "FB Resolved Sale",
                "insert_after": "custom_fb_order_line_ref",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_recipe_snapshot_json",
                "label": "Recipe Snapshot",
                "fieldtype": "Code",
                "options": "JSON",
                "insert_after": "custom_fb_resolved_sale",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_resolution_hash",
                "label": "Resolution Hash",
                "fieldtype": "Data",
                "insert_after": "custom_fb_recipe_snapshot_json",
                "read_only": 1,
                "translatable": 0,
            },
        ],
        "Sales Invoice Payment": [
            {
                "fieldname": "custom_fb_source_payment_id",
                "label": "F&B Source Payment ID",
                "fieldtype": "Data",
                "insert_after": "mode_of_payment",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "search_index": 1,
                "translatable": 0,
            },
        ],
        "Journal Entry": [
            {
                "fieldname": "custom_fb_return_event",
                "label": "F&B Return Event",
                "fieldtype": "Link",
                "options": "FB Return Event",
                "insert_after": "user_remark",
                "read_only": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_reconciliation_key",
                "label": "KoPOS QR Reconciliation Key",
                "fieldtype": "Data",
                "insert_after": "custom_fb_return_event",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "search_index": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_source_doctype",
                "label": "KoPOS QR Source Type",
                "fieldtype": "Link",
                "options": "DocType",
                "insert_after": "custom_kopos_qr_reconciliation_key",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_source_name",
                "label": "KoPOS QR Source",
                "fieldtype": "Dynamic Link",
                "options": "custom_kopos_qr_source_doctype",
                "insert_after": "custom_kopos_qr_source_doctype",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_fb_order",
                "label": "KoPOS QR F&B Order",
                "fieldtype": "Link",
                "options": "FB Order",
                "insert_after": "custom_kopos_qr_source_name",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_sales_invoice",
                "label": "KoPOS QR Sales Invoice",
                "fieldtype": "Link",
                "options": "Sales Invoice",
                "insert_after": "custom_kopos_qr_fb_order",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_amount_sen",
                "label": "KoPOS QR Amount (sen)",
                "fieldtype": "Int",
                "insert_after": "custom_kopos_qr_sales_invoice",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_currency",
                "label": "KoPOS QR Currency",
                "fieldtype": "Link",
                "options": "Currency",
                "insert_after": "custom_kopos_qr_amount_sen",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_failure_key",
                "label": "KoPOS QR Failure Accounting Key",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_currency",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "search_index": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_disposition",
                "label": "KoPOS QR Disposition",
                "fieldtype": "Select",
                "options": "\nreconciliation_failed",
                "insert_after": "custom_kopos_qr_failure_key",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_fb_order_payment",
                "label": "KoPOS QR F&B Order Payment Row",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_disposition",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_target_account",
                "label": "KoPOS QR Target Account",
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "custom_kopos_qr_fb_order_payment",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_cost_center",
                "label": "KoPOS QR Cost Center",
                "fieldtype": "Link",
                "options": "Cost Center",
                "insert_after": "custom_kopos_qr_target_account",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_source_account",
                "label": "KoPOS QR Source Account",
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "custom_kopos_qr_cost_center",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_prior_failure_journal",
                "label": "KoPOS Prior QR Failure Journal Entry",
                "fieldtype": "Link",
                "options": "Journal Entry",
                "insert_after": "custom_kopos_qr_source_account",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_failure_reason",
                "label": "KoPOS QR Failure Reason",
                "fieldtype": "Select",
                "options": (
                    "\nno_bank_transaction\namount_mismatch\nduplicate"
                    "\nwrong_device\ncustomer_dispute\nother"
                ),
                "insert_after": "custom_kopos_qr_prior_failure_journal",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_duplicate_key",
                "label": "KoPOS Duplicate QR Accounting Key",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_failure_reason",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "search_index": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_duplicate_stage",
                "label": "KoPOS Duplicate QR Accounting Stage",
                "fieldtype": "Select",
                "options": "\nliability_recognition\nrefund",
                "insert_after": "custom_kopos_qr_duplicate_key",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_provider_transaction",
                "label": "KoPOS Provider QR Transaction",
                "fieldtype": "Link",
                "options": "Maybank QR Transaction",
                "insert_after": "custom_kopos_qr_duplicate_stage",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_winning_transaction",
                "label": "KoPOS Winning QR Transaction",
                "fieldtype": "Link",
                "options": "Maybank QR Transaction",
                "insert_after": "custom_kopos_qr_provider_transaction",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_winning_channel",
                "label": "KoPOS Winning QR Channel",
                "fieldtype": "Select",
                "options": "\nmaybank_qr\nstatic_qr",
                "insert_after": "custom_kopos_qr_winning_transaction",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_winning_static_reconciliation",
                "label": "KoPOS Winning Static QR Reconciliation",
                "fieldtype": "Link",
                "options": "Manual QR Reconciliation",
                "insert_after": "custom_kopos_qr_winning_channel",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_provider_evidence_reference",
                "label": "KoPOS Provider Evidence Reference",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_winning_static_reconciliation",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_provider_evidence_sha256",
                "label": "KoPOS Provider Evidence SHA-256",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_provider_evidence_reference",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_provider_evidence_file",
                "label": "KoPOS Private Provider Evidence",
                "fieldtype": "Link",
                "options": "File",
                "insert_after": "custom_kopos_qr_provider_evidence_sha256",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
        ],
        "Stock Entry": [
            {
                "fieldname": "custom_kopos_inventory_command_id",
                "label": "KoPOS Inventory Command ID",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
            },
            {
                "fieldname": "custom_fb_projection_id",
                "label": "F&B Projection ID",
                "fieldtype": "Data",
                "insert_after": "stock_entry_type",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_order",
                "label": "F&B Order",
                "fieldtype": "Link",
                "options": "FB Order",
                "insert_after": "custom_fb_projection_id",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_resolved_sale",
                "label": "F&B Resolved Sale",
                "fieldtype": "Link",
                "options": "FB Resolved Sale",
                "insert_after": "custom_fb_order",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_event_project",
                "label": "Event/Project",
                "fieldtype": "Link",
                "options": "Project",
                "insert_after": "custom_fb_resolved_sale",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_shift",
                "label": "F&B Shift",
                "fieldtype": "Link",
                "options": "FB Shift",
                "insert_after": "custom_fb_event_project",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_reason_code",
                "label": "Reason Code",
                "fieldtype": "Data",
                "insert_after": "custom_fb_shift",
                "read_only": 1,
                "translatable": 0,
            },
        ],
        "Work Order": [
            {
                "fieldname": "custom_kopos_inventory_command_id",
                "label": "KoPOS Inventory Command ID",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
            },
        ],
        "Purchase Receipt": [
            {
                "fieldname": "custom_kopos_inventory_command_id",
                "label": "KoPOS Inventory Command ID",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
            },
        ],
    }

    create_custom_fields(custom_fields)


def remove_fb_custom_fields():
    fields_to_remove = [
        ("Company", "custom_kopos_qr_failure_variance_account"),
        ("Company", "custom_kopos_qr_duplicate_payment_clearing_account"),
        ("Company", "custom_kopos_qr_customer_liability_account"),
        ("Item", "custom_fb_item_role"),
        ("Item", "custom_fb_recipe_required"),
        ("Item", "custom_fb_default_recipe"),
        ("Item", "custom_fb_track_theoretical_stock"),
        ("Sales Invoice", "custom_fb_order"),
        ("Sales Invoice", "custom_fb_shift"),
        ("Sales Invoice", "custom_fb_device_id"),
        ("Sales Invoice", "custom_fb_event_project"),
        ("Sales Invoice", "custom_fb_idempotency_key"),
        ("Sales Invoice", "custom_fb_operational_status"),
        ("Sales Invoice", "custom_fb_void_idempotency_key"),
        ("Sales Invoice", "custom_fb_void_request_fingerprint"),
        ("Sales Invoice", "custom_fb_void_manager"),
        ("Sales Invoice", "custom_fb_void_approval_token_id"),
        ("Sales Invoice Item", "custom_fb_order_line_ref"),
        ("Sales Invoice Item", "custom_fb_resolved_sale"),
        ("Sales Invoice Item", "custom_fb_recipe_snapshot_json"),
        ("Sales Invoice Item", "custom_fb_resolution_hash"),
        ("Sales Invoice Payment", "custom_fb_source_payment_id"),
        ("Journal Entry", "custom_fb_return_event"),
        ("Journal Entry", "custom_kopos_qr_reconciliation_key"),
        ("Journal Entry", "custom_kopos_qr_source_doctype"),
        ("Journal Entry", "custom_kopos_qr_source_name"),
        ("Journal Entry", "custom_kopos_qr_fb_order"),
        ("Journal Entry", "custom_kopos_qr_sales_invoice"),
        ("Journal Entry", "custom_kopos_qr_amount_sen"),
        ("Journal Entry", "custom_kopos_qr_currency"),
        ("Journal Entry", "custom_kopos_qr_failure_key"),
        ("Journal Entry", "custom_kopos_qr_disposition"),
        ("Journal Entry", "custom_kopos_qr_fb_order_payment"),
        ("Journal Entry", "custom_kopos_qr_target_account"),
        ("Journal Entry", "custom_kopos_qr_cost_center"),
        ("Journal Entry", "custom_kopos_qr_source_account"),
        ("Journal Entry", "custom_kopos_qr_prior_failure_journal"),
        ("Journal Entry", "custom_kopos_qr_failure_reason"),
        ("Journal Entry", "custom_kopos_qr_duplicate_key"),
        ("Journal Entry", "custom_kopos_qr_duplicate_stage"),
        ("Journal Entry", "custom_kopos_qr_provider_transaction"),
        ("Journal Entry", "custom_kopos_qr_winning_transaction"),
        ("Journal Entry", "custom_kopos_qr_winning_channel"),
        ("Journal Entry", "custom_kopos_qr_winning_static_reconciliation"),
        ("Journal Entry", "custom_kopos_qr_provider_evidence_reference"),
        ("Journal Entry", "custom_kopos_qr_provider_evidence_file"),
        ("Journal Entry", "custom_kopos_qr_provider_evidence_sha256"),
        ("Stock Entry", "custom_fb_projection_id"),
        ("Stock Entry", "custom_kopos_inventory_command_id"),
        ("Stock Entry", "custom_fb_order"),
        ("Stock Entry", "custom_fb_resolved_sale"),
        ("Stock Entry", "custom_fb_event_project"),
        ("Stock Entry", "custom_fb_shift"),
        ("Stock Entry", "custom_fb_reason_code"),
        ("Material Request", "custom_kopos_inventory_fingerprint"),
        ("Purchase Order", "custom_kopos_inventory_fingerprint"),
        ("Purchase Order", "custom_kopos_material_request"),
        ("Purchase Order", "custom_kopos_plan_hash"),
        ("Purchase Order", "custom_kopos_policy_hash"),
        ("Purchase Order", "custom_kopos_quotation_hash"),
        ("Work Order", "custom_kopos_inventory_command_id"),
        ("Purchase Receipt", "custom_kopos_inventory_command_id"),
    ]

    for doctype, fieldname in fields_to_remove:
        try:
            frappe.db.delete("Custom Field", {"name": f"{doctype}-{fieldname}"})
        except Exception:
            pass

    frappe.db.commit()
