from __future__ import annotations

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def create_fb_custom_fields():
    custom_fields = {
        "Company": [
            {
                "fieldname": "custom_kopos_qr_failure_variance_account",
                "label": "KoPOS QR Failure Variance Account",
                "description": (
                    "Company-scoped Expense ledger debited only when a pending QR "
                    "settlement is terminally failed with submitted accounting evidence"
                ),
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "default_currency",
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_duplicate_payment_clearing_account",
                "label": "KoPOS Duplicate QR Bank/Clearing Account",
                "description": (
                    "Company-scoped MYR Asset ledger debited when an additional "
                    "provider-paid Automatic QR attempt is recognized and credited "
                    "only when its exact provider refund is recorded"
                ),
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "custom_kopos_qr_failure_variance_account",
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_customer_liability_account",
                "label": "KoPOS QR Customer Refund Liability Account",
                "description": (
                    "Company-scoped MYR Liability ledger credited before a duplicate "
                    "provider payment can be marked refund_required"
                ),
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "custom_kopos_qr_duplicate_payment_clearing_account",
                "no_copy": 1,
                "translatable": 0,
            },
        ],
        "Item": [
            {
                "fieldname": "custom_fb_item_role",
                "label": "F&B Item Role",
                "fieldtype": "Select",
                "options": "\nSellable Drink\nIngredient\nPrep Item\nPackaging\nTool\nAsset Managed Gear",
                "insert_after": "item_group",
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_recipe_required",
                "label": "F&B Recipe Required",
                "fieldtype": "Check",
                "default": "0",
                "insert_after": "custom_fb_item_role",
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_default_recipe",
                "label": "F&B Default Recipe",
                "fieldtype": "Link",
                "options": "FB Recipe",
                "insert_after": "custom_fb_recipe_required",
                "depends_on": "eval:doc.custom_fb_recipe_required == 1",
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_track_theoretical_stock",
                "label": "Track Theoretical Stock",
                "fieldtype": "Check",
                "default": "0",
                "insert_after": "custom_fb_default_recipe",
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_inventory_excluded",
                "label": "Exclude From Inventory Autopilot",
                "description": "Explicitly approved non-inventory sellable. It remains commercial-only and cannot be projected or forecast.",
                "fieldtype": "Check",
                "default": "0",
                "insert_after": "custom_fb_track_theoretical_stock",
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_inventory_exclusion_reason",
                "label": "Inventory Exclusion Reason",
                "fieldtype": "Small Text",
                "depends_on": "eval:doc.custom_fb_inventory_excluded == 1",
                "mandatory_depends_on": "eval:doc.custom_fb_inventory_excluded == 1",
                "insert_after": "custom_fb_inventory_excluded",
                "translatable": 0,
            },
        ],
        "Item Group": [
            {
                "fieldname": "custom_kopos_count_frequency",
                "label": "Inventory Count Frequency",
                "fieldtype": "Select",
                "options": "\nDaily\nSelected Weekdays\nWeekly\nOff",
                "description": (
                    "Company Director minimum blind-count cadence for this stock group. "
                    "Blank is unconfigured; JiJi never guesses a cadence."
                ),
                "insert_after": "is_group",
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_count_weekdays",
                "label": "Inventory Count Weekdays",
                "fieldtype": "Small Text",
                "description": (
                    "Comma-separated weekday names such as Mon,Wed,Fri. Required for "
                    "Selected Weekdays and exactly one day is required for Weekly."
                ),
                "depends_on": (
                    "eval:doc.custom_kopos_count_frequency == 'Selected Weekdays' "
                    "|| doc.custom_kopos_count_frequency == 'Weekly'"
                ),
                "insert_after": "custom_kopos_count_frequency",
                "translatable": 0,
            },
        ],
        "Item Reorder": [
            {
                "fieldname": "custom_kopos_source_warehouse",
                "label": "KoPOS Transfer Source Warehouse",
                "description": "For a Transfer reorder row, the exact outlet warehouse allowed to supply this destination. JiJi never guesses a source.",
                "fieldtype": "Link",
                "options": "Warehouse",
                "insert_after": "warehouse_group",
                "depends_on": "eval:doc.material_request_type == 'Transfer'",
                "mandatory_depends_on": "eval:doc.material_request_type == 'Transfer'",
                "translatable": 0,
            },
        ],
        "BOM": [
            {
                "fieldname": "custom_kopos_autoprep_enabled",
                "label": "KoPOS Automatic Batch Preparation",
                "description": "When enabled, an Active outlet policy may surface a preparation alert when usable stock falls below the ready level. Staff acceptance creates one Draft Work Order.",
                "fieldtype": "Check",
                "default": "0",
                "insert_after": "is_active",
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_batch_qty",
                "label": "KoPOS Batch Quantity",
                "description": "Quantity produced by one routine batch. Blank uses the BOM quantity.",
                "fieldtype": "Float",
                "insert_after": "custom_kopos_autoprep_enabled",
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_min_ready_qty",
                "label": "KoPOS Minimum Ready Quantity",
                "description": "Usable stock threshold that triggers a routine batch. Blank uses the batch quantity.",
                "fieldtype": "Float",
                "insert_after": "custom_kopos_batch_qty",
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_preparation_lead_minutes",
                "label": "KoPOS Preparation Lead (minutes)",
                "description": "Expected preparation time shown to staff when the Work Order is surfaced on POS.",
                "fieldtype": "Int",
                "insert_after": "custom_kopos_min_ready_qty",
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_preparation_variance_percent",
                "label": "KoPOS Preparation Variance Ceiling (%)",
                "description": "Optional director-approved percentage ceiling for usable-yield or waste variance. Leave blank only when the outlet policy supplies a ceiling.",
                "fieldtype": "Percent",
                "insert_after": "custom_kopos_preparation_lead_minutes",
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_preparation_instructions",
                "label": "KoPOS Preparation Instructions",
                "description": "Short approved instructions shown to staff for this prepared batch.",
                "fieldtype": "Small Text",
                "insert_after": "custom_kopos_preparation_lead_minutes",
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_preparation_fingerprint",
                "label": "KoPOS Preparation Fingerprint",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
                "insert_after": "custom_kopos_preparation_instructions",
                "translatable": 0,
            },
        ],
        "Sales Invoice": [
            {
                "fieldname": "custom_fb_order",
                "label": "F&B Order",
                "fieldtype": "Link",
                "options": "FB Order",
                "insert_after": "customer",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_shift",
                "label": "F&B Shift",
                "fieldtype": "Link",
                "options": "FB Shift",
                "insert_after": "custom_fb_order",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_device_id",
                "label": "Device ID",
                "fieldtype": "Data",
                "insert_after": "custom_fb_shift",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_event_project",
                "label": "Event/Project",
                "fieldtype": "Link",
                "options": "Project",
                "insert_after": "custom_fb_device_id",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_idempotency_key",
                "label": "Idempotency Key",
                "fieldtype": "Data",
                "insert_after": "custom_fb_event_project",
                "read_only": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_operational_status",
                "label": "Operational Status",
                "fieldtype": "Select",
                "options": "\nDraft\nSubmitted\nCancelled",
                "insert_after": "custom_fb_idempotency_key",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_void_idempotency_key",
                "label": "Void Idempotency Key",
                "fieldtype": "Data",
                "insert_after": "custom_fb_operational_status",
                "read_only": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_void_request_fingerprint",
                "label": "Void Request Fingerprint",
                "fieldtype": "Data",
                "insert_after": "custom_fb_void_idempotency_key",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_void_manager",
                "label": "Void Approved By Manager",
                "fieldtype": "Link",
                "options": "User",
                "insert_after": "custom_fb_void_request_fingerprint",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_void_approval_token_id",
                "label": "Void Approval Token ID",
                "fieldtype": "Data",
                "insert_after": "custom_fb_void_manager",
                "read_only": 1,
                "unique": 1,
                "translatable": 0,
            },
        ],
        "Material Request": [
            {
                "fieldname": "custom_kopos_inventory_fingerprint",
                "label": "KoPOS Inventory Fingerprint",
                "fieldtype": "Data",
                "unique": 1,
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_transit_warehouse",
                "label": "KoPOS Transit Warehouse",
                "description": "Required route for a submitted inter-outlet Material Transfer. POS execution cannot change it.",
                "fieldtype": "Link",
                "options": "Warehouse",
                "insert_after": "custom_kopos_inventory_fingerprint",
                "no_copy": 1,
            },
        ],
        "Purchase Order": [
            {
                "fieldname": "custom_kopos_inventory_fingerprint",
                "label": "KoPOS Inventory Fingerprint",
                "fieldtype": "Data",
                "unique": 1,
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_material_request",
                "label": "KoPOS Material Request",
                "fieldtype": "Link",
                "options": "Material Request",
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_plan_hash",
                "label": "KoPOS Plan Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_policy_hash",
                "label": "KoPOS Policy Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_quotation_hash",
                "label": "KoPOS Quotation Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "no_copy": 1,
            },
        ],
        "Sales Invoice Item": [
            {
                "fieldname": "custom_fb_order_line_ref",
                "label": "F&B Order Line Ref",
                "fieldtype": "Data",
                "insert_after": "item_name",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_resolved_sale",
                "label": "F&B Resolved Sale",
                "fieldtype": "Link",
                "options": "FB Resolved Sale",
                "insert_after": "custom_fb_order_line_ref",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_recipe_snapshot_json",
                "label": "Recipe Snapshot",
                "fieldtype": "Code",
                "options": "JSON",
                "insert_after": "custom_fb_resolved_sale",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_resolution_hash",
                "label": "Resolution Hash",
                "fieldtype": "Data",
                "insert_after": "custom_fb_recipe_snapshot_json",
                "read_only": 1,
                "translatable": 0,
            },
        ],
        "Sales Invoice Payment": [
            {
                "fieldname": "custom_fb_source_payment_id",
                "label": "F&B Source Payment ID",
                "fieldtype": "Data",
                "insert_after": "mode_of_payment",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "search_index": 1,
                "translatable": 0,
            },
        ],
        "Journal Entry": [
            {
                "fieldname": "custom_fb_return_event",
                "label": "F&B Return Event",
                "fieldtype": "Link",
                "options": "FB Return Event",
                "insert_after": "user_remark",
                "read_only": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_reconciliation_key",
                "label": "KoPOS QR Reconciliation Key",
                "fieldtype": "Data",
                "insert_after": "custom_fb_return_event",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "search_index": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_source_doctype",
                "label": "KoPOS QR Source Type",
                "fieldtype": "Link",
                "options": "DocType",
                "insert_after": "custom_kopos_qr_reconciliation_key",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_source_name",
                "label": "KoPOS QR Source",
                "fieldtype": "Dynamic Link",
                "options": "custom_kopos_qr_source_doctype",
                "insert_after": "custom_kopos_qr_source_doctype",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_fb_order",
                "label": "KoPOS QR F&B Order",
                "fieldtype": "Link",
                "options": "FB Order",
                "insert_after": "custom_kopos_qr_source_name",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_sales_invoice",
                "label": "KoPOS QR Sales Invoice",
                "fieldtype": "Link",
                "options": "Sales Invoice",
                "insert_after": "custom_kopos_qr_fb_order",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_amount_sen",
                "label": "KoPOS QR Amount (sen)",
                "fieldtype": "Int",
                "insert_after": "custom_kopos_qr_sales_invoice",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_currency",
                "label": "KoPOS QR Currency",
                "fieldtype": "Link",
                "options": "Currency",
                "insert_after": "custom_kopos_qr_amount_sen",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_failure_key",
                "label": "KoPOS QR Failure Accounting Key",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_currency",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "search_index": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_disposition",
                "label": "KoPOS QR Disposition",
                "fieldtype": "Select",
                "options": "\nreconciliation_failed",
                "insert_after": "custom_kopos_qr_failure_key",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_fb_order_payment",
                "label": "KoPOS QR F&B Order Payment Row",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_disposition",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_target_account",
                "label": "KoPOS QR Target Account",
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "custom_kopos_qr_fb_order_payment",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_cost_center",
                "label": "KoPOS QR Cost Center",
                "fieldtype": "Link",
                "options": "Cost Center",
                "insert_after": "custom_kopos_qr_target_account",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_source_account",
                "label": "KoPOS QR Source Account",
                "fieldtype": "Link",
                "options": "Account",
                "insert_after": "custom_kopos_qr_cost_center",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_prior_failure_journal",
                "label": "KoPOS Prior QR Failure Journal Entry",
                "fieldtype": "Link",
                "options": "Journal Entry",
                "insert_after": "custom_kopos_qr_source_account",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_failure_reason",
                "label": "KoPOS QR Failure Reason",
                "fieldtype": "Select",
                "options": (
                    "\nno_bank_transaction\namount_mismatch\nduplicate"
                    "\nwrong_device\ncustomer_dispute\nother"
                ),
                "insert_after": "custom_kopos_qr_prior_failure_journal",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_duplicate_key",
                "label": "KoPOS Duplicate QR Accounting Key",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_failure_reason",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "search_index": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_duplicate_stage",
                "label": "KoPOS Duplicate QR Accounting Stage",
                "fieldtype": "Select",
                "options": "\nliability_recognition\nrefund",
                "insert_after": "custom_kopos_qr_duplicate_key",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_provider_transaction",
                "label": "KoPOS Provider QR Transaction",
                "fieldtype": "Link",
                "options": "Maybank QR Transaction",
                "insert_after": "custom_kopos_qr_duplicate_stage",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_winning_transaction",
                "label": "KoPOS Winning QR Transaction",
                "fieldtype": "Link",
                "options": "Maybank QR Transaction",
                "insert_after": "custom_kopos_qr_provider_transaction",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_winning_channel",
                "label": "KoPOS Winning QR Channel",
                "fieldtype": "Select",
                "options": "\nmaybank_qr\nstatic_qr",
                "insert_after": "custom_kopos_qr_winning_transaction",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_winning_static_reconciliation",
                "label": "KoPOS Winning Static QR Reconciliation",
                "fieldtype": "Link",
                "options": "Manual QR Reconciliation",
                "insert_after": "custom_kopos_qr_winning_channel",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_provider_evidence_reference",
                "label": "KoPOS Provider Evidence Reference",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_winning_static_reconciliation",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_provider_evidence_sha256",
                "label": "KoPOS Provider Evidence SHA-256",
                "fieldtype": "Data",
                "insert_after": "custom_kopos_qr_provider_evidence_reference",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_qr_provider_evidence_file",
                "label": "KoPOS Private Provider Evidence",
                "fieldtype": "Link",
                "options": "File",
                "insert_after": "custom_kopos_qr_provider_evidence_sha256",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "translatable": 0,
            },
        ],
        "Stock Entry": [
            {
                "fieldname": "custom_kopos_inventory_command_id",
                "label": "KoPOS Inventory Command ID",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
            },
            {
                "fieldname": "custom_kopos_inventory_payload_hash",
                "label": "KoPOS Inventory Payload Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "insert_after": "custom_kopos_inventory_command_id",
            },
            {
                "fieldname": "custom_kopos_transfer_material_request",
                "label": "KoPOS Transfer Material Request",
                "fieldtype": "Link",
                "options": "Material Request",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "insert_after": "custom_kopos_inventory_command_id",
            },
            {
                "fieldname": "custom_kopos_preparation_waste_qty",
                "label": "KoPOS Preparation Waste Quantity",
                "fieldtype": "Float",
                "read_only": 1,
                "no_copy": 1,
                "insert_after": "custom_kopos_transfer_material_request",
            },
            {
                "fieldname": "custom_fb_projection_id",
                "label": "F&B Projection ID",
                "fieldtype": "Data",
                "insert_after": "stock_entry_type",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_order",
                "label": "F&B Order",
                "fieldtype": "Link",
                "options": "FB Order",
                "insert_after": "custom_fb_projection_id",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_resolved_sale",
                "label": "F&B Resolved Sale",
                "fieldtype": "Link",
                "options": "FB Resolved Sale",
                "insert_after": "custom_fb_order",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_event_project",
                "label": "Event/Project",
                "fieldtype": "Link",
                "options": "Project",
                "insert_after": "custom_fb_resolved_sale",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_shift",
                "label": "F&B Shift",
                "fieldtype": "Link",
                "options": "FB Shift",
                "insert_after": "custom_fb_event_project",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_fb_reason_code",
                "label": "Reason Code",
                "fieldtype": "Data",
                "insert_after": "custom_fb_shift",
                "read_only": 1,
                "translatable": 0,
            },
            {
                "fieldname": "custom_kopos_inventory_recorded_by",
                "label": "KoPOS Inventory Recorded By",
                "fieldtype": "Link",
                "options": "User",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_inventory_confirmed_by",
                "label": "KoPOS Inventory Confirmed By",
                "fieldtype": "Link",
                "options": "User",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
        ],
        "Stock Entry Detail": [
            {
                "fieldname": "custom_kopos_transfer_request_item",
                "label": "KoPOS Transfer Material Request Item",
                "fieldtype": "Link",
                "options": "Material Request Item",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
        ],
        "Work Order": [
            {
                "fieldname": "custom_kopos_inventory_command_id",
                "label": "KoPOS Inventory Command ID",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
            },
            {
                "fieldname": "custom_kopos_inventory_payload_hash",
                "label": "KoPOS Inventory Payload Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "insert_after": "custom_kopos_inventory_command_id",
            },
            {
                "fieldname": "custom_kopos_preparation_fingerprint",
                "label": "KoPOS Preparation Fingerprint",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
            },
            {
                "fieldname": "custom_kopos_inventory_recorded_by",
                "label": "KoPOS Inventory Recorded By",
                "fieldtype": "Link",
                "options": "User",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_inventory_confirmed_by",
                "label": "KoPOS Inventory Confirmed By",
                "fieldtype": "Link",
                "options": "User",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
        ],
        "Purchase Receipt": [
            {
                "fieldname": "custom_kopos_inventory_command_id",
                "label": "KoPOS Inventory Command ID",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "unique": 1,
            },
            {
                "fieldname": "custom_kopos_inventory_payload_hash",
                "label": "KoPOS Inventory Payload Hash",
                "fieldtype": "Data",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
                "insert_after": "custom_kopos_inventory_command_id",
            },
            {
                "fieldname": "custom_kopos_inventory_recorded_by",
                "label": "KoPOS Inventory Recorded By",
                "fieldtype": "Link",
                "options": "User",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
            {
                "fieldname": "custom_kopos_inventory_confirmed_by",
                "label": "KoPOS Inventory Confirmed By",
                "fieldtype": "Link",
                "options": "User",
                "read_only": 1,
                "hidden": 1,
                "no_copy": 1,
            },
        ],
    }

    create_custom_fields(custom_fields)


def remove_fb_custom_fields():
    fields_to_remove = [
        ("Company", "custom_kopos_qr_failure_variance_account"),
        ("Company", "custom_kopos_qr_duplicate_payment_clearing_account"),
        ("Company", "custom_kopos_qr_customer_liability_account"),
        ("Item", "custom_fb_item_role"),
        ("Item", "custom_fb_recipe_required"),
        ("Item", "custom_fb_default_recipe"),
        ("Item", "custom_fb_track_theoretical_stock"),
        ("Item", "custom_fb_inventory_excluded"),
        ("Item", "custom_fb_inventory_exclusion_reason"),
        ("Item Group", "custom_kopos_count_frequency"),
        ("Item Group", "custom_kopos_count_weekdays"),
        ("BOM", "custom_kopos_autoprep_enabled"),
        ("BOM", "custom_kopos_batch_qty"),
        ("BOM", "custom_kopos_min_ready_qty"),
        ("BOM", "custom_kopos_preparation_lead_minutes"),
        ("BOM", "custom_kopos_preparation_variance_percent"),
        ("BOM", "custom_kopos_preparation_instructions"),
        ("BOM", "custom_kopos_preparation_fingerprint"),
        ("Sales Invoice", "custom_fb_order"),
        ("Sales Invoice", "custom_fb_shift"),
        ("Sales Invoice", "custom_fb_device_id"),
        ("Sales Invoice", "custom_fb_event_project"),
        ("Sales Invoice", "custom_fb_idempotency_key"),
        ("Sales Invoice", "custom_fb_operational_status"),
        ("Sales Invoice", "custom_fb_void_idempotency_key"),
        ("Sales Invoice", "custom_fb_void_request_fingerprint"),
        ("Sales Invoice", "custom_fb_void_manager"),
        ("Sales Invoice", "custom_fb_void_approval_token_id"),
        ("Sales Invoice Item", "custom_fb_order_line_ref"),
        ("Sales Invoice Item", "custom_fb_resolved_sale"),
        ("Sales Invoice Item", "custom_fb_recipe_snapshot_json"),
        ("Sales Invoice Item", "custom_fb_resolution_hash"),
        ("Sales Invoice Payment", "custom_fb_source_payment_id"),
        ("Journal Entry", "custom_fb_return_event"),
        ("Journal Entry", "custom_kopos_qr_reconciliation_key"),
        ("Journal Entry", "custom_kopos_qr_source_doctype"),
        ("Journal Entry", "custom_kopos_qr_source_name"),
        ("Journal Entry", "custom_kopos_qr_fb_order"),
        ("Journal Entry", "custom_kopos_qr_sales_invoice"),
        ("Journal Entry", "custom_kopos_qr_amount_sen"),
        ("Journal Entry", "custom_kopos_qr_currency"),
        ("Journal Entry", "custom_kopos_qr_failure_key"),
        ("Journal Entry", "custom_kopos_qr_disposition"),
        ("Journal Entry", "custom_kopos_qr_fb_order_payment"),
        ("Journal Entry", "custom_kopos_qr_target_account"),
        ("Journal Entry", "custom_kopos_qr_cost_center"),
        ("Journal Entry", "custom_kopos_qr_source_account"),
        ("Journal Entry", "custom_kopos_qr_prior_failure_journal"),
        ("Journal Entry", "custom_kopos_qr_failure_reason"),
        ("Journal Entry", "custom_kopos_qr_duplicate_key"),
        ("Journal Entry", "custom_kopos_qr_duplicate_stage"),
        ("Journal Entry", "custom_kopos_qr_provider_transaction"),
        ("Journal Entry", "custom_kopos_qr_winning_transaction"),
        ("Journal Entry", "custom_kopos_qr_winning_channel"),
        ("Journal Entry", "custom_kopos_qr_winning_static_reconciliation"),
        ("Journal Entry", "custom_kopos_qr_provider_evidence_reference"),
        ("Journal Entry", "custom_kopos_qr_provider_evidence_file"),
        ("Journal Entry", "custom_kopos_qr_provider_evidence_sha256"),
        ("Stock Entry", "custom_fb_projection_id"),
        ("Stock Entry", "custom_kopos_inventory_command_id"),
        ("Stock Entry", "custom_kopos_inventory_payload_hash"),
        ("Stock Entry", "custom_kopos_transfer_material_request"),
        ("Stock Entry", "custom_kopos_preparation_waste_qty"),
        ("Stock Entry", "custom_fb_order"),
        ("Stock Entry", "custom_fb_resolved_sale"),
        ("Stock Entry", "custom_fb_event_project"),
        ("Stock Entry", "custom_fb_shift"),
        ("Stock Entry", "custom_fb_reason_code"),
        ("Material Request", "custom_kopos_inventory_fingerprint"),
        ("Material Request", "custom_kopos_transit_warehouse"),
        ("Item Reorder", "custom_kopos_source_warehouse"),
        ("Purchase Order", "custom_kopos_inventory_fingerprint"),
        ("Purchase Order", "custom_kopos_material_request"),
        ("Purchase Order", "custom_kopos_plan_hash"),
        ("Purchase Order", "custom_kopos_policy_hash"),
        ("Purchase Order", "custom_kopos_quotation_hash"),
        ("Work Order", "custom_kopos_inventory_command_id"),
        ("Work Order", "custom_kopos_inventory_payload_hash"),
        ("Work Order", "custom_kopos_preparation_fingerprint"),
        ("Work Order", "custom_kopos_inventory_recorded_by"),
        ("Work Order", "custom_kopos_inventory_confirmed_by"),
        ("Purchase Receipt", "custom_kopos_inventory_command_id"),
        ("Purchase Receipt", "custom_kopos_inventory_payload_hash"),
        ("Purchase Receipt", "custom_kopos_inventory_recorded_by"),
        ("Purchase Receipt", "custom_kopos_inventory_confirmed_by"),
        ("Stock Entry", "custom_kopos_inventory_recorded_by"),
        ("Stock Entry", "custom_kopos_inventory_confirmed_by"),
        ("Stock Entry Detail", "custom_kopos_transfer_request_item"),
    ]

    for doctype, fieldname in fields_to_remove:
        try:
            frappe.db.delete("Custom Field", {"name": f"{doctype}-{fieldname}"})
        except Exception:
            pass

    frappe.db.commit()
